{"uuid": "6ef28758-acc6-4b9f-ba21-1d60aaf2ccc8", "children": ["761037f1-91a2-4b77-9d3b-c3a1f43aa101", "db2336ee-8829-47a9-966a-e34e156e1169", "f531193e-c1e5-44e6-a780-f52f37b61e26", "0767fb6f-fd87-4126-bcda-533aef7e0a9d", "3dabdd55-03e6-42a3-95c0-6cd46fe68e28", "87e7febd-a309-4b5d-b311-5d676694a0e0", "62f65286-dec5-4588-b203-f594d2eb1079", "fae08e5c-a943-48d3-853a-452b0bcf268c"], "befores": [{"name": "init_web_driver", "status": "broken", "statusDetails": {"message": "TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'\n", "trace": "  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Final_Proj_Aut_Py\\test_cases\\conftest.py\", line 42, in init_web_driver\n    edriver = get_web_driver()\n              ^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Final_Proj_Aut_Py\\test_cases\\conftest.py\", line 96, in get_web_driver\n    driver = get_chrome()\n             ^^^^^^^^^^^^\n  File \"C:\\Automation\\Final_Proj_Aut_Py\\test_cases\\conftest.py\", line 125, in get_chrome\n    chrome_driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))  # Selenium 4.x\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1682172167974, "stop": 1682172172034}], "start": 1682172167974, "stop": 1682172172287}