{"name": "TC03: Negative test - Verify transaction is deleted", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error (An unknown server-side error occurred. status='false'. Failed to complete internal method: 'elementSendText args: [NATIVE, xpath=(//*[@resource-id='etTerm' or @id='etTerm'])[1], 0, 5]', details: Failed to send text to 'xpath=(//*[@resource-id='etTerm' or @id='etTerm'])[1]'. )", "trace": "self = <test_cases.test_mobile.TestMobile object at 0x0000024490D16A50>\n\n    @allure.title(\"TC03: Negative test - Verify transaction is deleted\")\n    @allure.description(\"this test verify transaction deleted transaction doesn't appears in the app\")\n    @pytest.mark.sanity\n    def test_delete_saved_trans(self):\n        MobileFlows.swipe_screen(Direction.RIGHT)\n>       MobileFlows.mortgage_flow('1000', '5', '2.5', Save.YES)\n\ntest_mobile.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\workflows\\mobile_flows.py:26: in mortgage_flow\n    MobileActions.update_text(page.mobile_calculator.get_term(), term)\n..\\extensions\\ui_actiuons.py:24: in update_text\n    elem.send_keys(value)\n..\\..\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py:232: in send_keys\n    self._dispatch(\"change_value_of\", (self._webelement, self._driver), \"send_keys\", value)\n..\\..\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py:294: in _dispatch\n    raise e\n..\\..\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py:291: in _dispatch\n    result = getattr(self._webelement, d_call)(*d_args)\n..\\..\\Hobiz_Automation\\venv\\Lib\\site-packages\\appium\\webdriver\\webelement.py:218: in send_keys\n    self._execute(RemoteCommand.SEND_KEYS_TO_ELEMENT, {'text': ''.join(keys), 'value': keys})\n..\\..\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py:633: in _execute\n    return self._parent.execute(command, params)\n..\\..\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:321: in execute\n    self.error_handler.check_response(response)\n..\\..\\Hobiz_Automation\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py:31: in check_response\n    raise wde\n..\\..\\Hobiz_Automation\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py:26: in check_response\n    super().check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x0000024490CD62D0>\nresponse = {'status': 500, 'value': '{\"sessionId\":\"fe1ca9a3-368d-4b41-8bab-1afbf669c19a\",\"value\":{\"message\":\"unknown error (An un...]\\', details: Failed to send text to \\'xpath=(//*[@resource-id=\\'etTerm\\' or @id=\\'etTerm\\'])[1]\\'. ) \"},\"status\":13}'}\n\n    def check_response(self, response):\n        \"\"\"\n        Checks that a JSON response from the WebDriver does not have an error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get('status', None)\n        if status is None or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get('value', None)\n            if value_json and isinstance(value_json, basestring):\n                import json\n                try:\n                    value = json.loads(value_json)\n                    if len(value.keys()) == 1:\n                        value = value['value']\n                    status = value.get('error', None)\n                    if status is None:\n                        status = value[\"status\"]\n                        message = value[\"value\"]\n                        if not isinstance(message, basestring):\n                            value = message\n                            message = message.get('message')\n                    else:\n                        message = value.get('message', None)\n                except ValueError:\n                    pass\n    \n        exception_class = ErrorInResponseException\n        if status in ErrorCode.NO_SUCH_ELEMENT:\n            exception_class = NoSuchElementException\n        elif status in ErrorCode.NO_SUCH_FRAME:\n            exception_class = NoSuchFrameException\n        elif status in ErrorCode.NO_SUCH_WINDOW:\n            exception_class = NoSuchWindowException\n        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:\n            exception_class = StaleElementReferenceException\n        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:\n            exception_class = ElementNotVisibleException\n        elif status in ErrorCode.INVALID_ELEMENT_STATE:\n            exception_class = InvalidElementStateException\n        elif status in ErrorCode.INVALID_SELECTOR \\\n                or status in ErrorCode.INVALID_XPATH_SELECTOR \\\n                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:\n            exception_class = InvalidSelectorException\n        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:\n            exception_class = ElementNotSelectableException\n        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:\n            exception_class = ElementNotInteractableException\n        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:\n            exception_class = InvalidCookieDomainException\n        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:\n            exception_class = UnableToSetCookieException\n        elif status in ErrorCode.TIMEOUT:\n            exception_class = TimeoutException\n        elif status in ErrorCode.SCRIPT_TIMEOUT:\n            exception_class = TimeoutException\n        elif status in ErrorCode.UNKNOWN_ERROR:\n            exception_class = WebDriverException\n        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:\n            exception_class = UnexpectedAlertPresentException\n        elif status in ErrorCode.NO_ALERT_OPEN:\n            exception_class = NoAlertPresentException\n        elif status in ErrorCode.IME_NOT_AVAILABLE:\n            exception_class = ImeNotAvailableException\n        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:\n            exception_class = ImeActivationFailedException\n        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:\n            exception_class = MoveTargetOutOfBoundsException\n        elif status in ErrorCode.JAVASCRIPT_ERROR:\n            exception_class = JavascriptException\n        elif status in ErrorCode.SESSION_NOT_CREATED:\n            exception_class = SessionNotCreatedException\n        elif status in ErrorCode.INVALID_ARGUMENT:\n            exception_class = InvalidArgumentException\n        elif status in ErrorCode.NO_SUCH_COOKIE:\n            exception_class = NoSuchCookieException\n        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:\n            exception_class = ScreenshotException\n        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:\n            exception_class = ElementClickInterceptedException\n        elif status in ErrorCode.INSECURE_CERTIFICATE:\n            exception_class = InsecureCertificateException\n        elif status in ErrorCode.INVALID_COORDINATES:\n            exception_class = InvalidCoordinatesException\n        elif status in ErrorCode.INVALID_SESSION_ID:\n            exception_class = InvalidSessionIdException\n        elif status in ErrorCode.UNKNOWN_METHOD:\n            exception_class = UnknownMethodException\n        else:\n            exception_class = WebDriverException\n        if value == '' or value is None:\n            value = response['value']\n        if isinstance(value, basestring):\n            if exception_class == ErrorInResponseException:\n                raise exception_class(response, value)\n            raise exception_class(value)\n        if message == \"\" and 'message' in value:\n            message = value['message']\n    \n        screen = None\n        if 'screen' in value:\n            screen = value['screen']\n    \n        stacktrace = None\n        if 'stackTrace' in value and value['stackTrace']:\n            stacktrace = []\n            try:\n                for frame in value['stackTrace']:\n                    line = self._value_or_default(frame, 'lineNumber', '')\n                    file = self._value_or_default(frame, 'fileName', '<anonymous>')\n                    if line:\n                        file = \"%s:%s\" % (file, line)\n                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')\n                    if 'className' in frame:\n                        meth = \"%s.%s\" % (frame['className'], meth)\n                    msg = \"    at %s (%s)\"\n                    msg = msg % (meth, file)\n                    stacktrace.append(msg)\n            except TypeError:\n                pass\n        if exception_class == ErrorInResponseException:\n            raise exception_class(response, message)\n        elif exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if 'data' in value:\n                alert_text = value['data'].get('text')\n            elif 'alert' in value:\n                alert_text = value['alert'].get('text')\n            raise exception_class(message, screen, stacktrace, alert_text)\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error (An unknown server-side error occurred. status='false'. Failed to complete internal method: 'elementSendText args: [NATIVE, xpath=(//*[@resource-id='etTerm' or @id='etTerm'])[1], 0, 5]', details: Failed to send text to 'xpath=(//*[@resource-id='etTerm' or @id='etTerm'])[1]'. )\n\n..\\..\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:242: WebDriverException"}, "description": "this test verify transaction deleted transaction doesn't appears in the app", "steps": [{"name": "Swipe the page", "status": "passed", "steps": [{"name": "Swipe screen", "status": "passed", "parameters": [{"name": "start_x", "value": "108.0"}, {"name": "start_y", "value": "1320.0"}, {"name": "end_x", "value": "972.0"}, {"name": "end_y", "value": "1320.0"}, {"name": "duration", "value": "200"}], "start": 1695030667127, "stop": 1695030667746}], "parameters": [{"name": "direction", "value": "'right'"}], "start": 1695030667126, "stop": 1695030667746}, {"name": "Fill in mortgage details flow", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error (An unknown server-side error occurred. status='false'. Failed to complete internal method: 'elementSendText args: [NATIVE, xpath=(//*[@resource-id='etTerm' or @id='etTerm'])[1], 0, 5]', details: Failed to send text to 'xpath=(//*[@resource-id='etTerm' or @id='etTerm'])[1]'. ) \n\n", "trace": "  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Final_Proj_Aut_Py\\workflows\\mobile_flows.py\", line 26, in mortgage_flow\n    MobileActions.update_text(page.mobile_calculator.get_term(), term)\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Final_Proj_Aut_Py\\extensions\\ui_actiuons.py\", line 24, in update_text\n    elem.send_keys(value)\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 232, in send_keys\n    self._dispatch(\"change_value_of\", (self._webelement, self._driver), \"send_keys\", value)\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 294, in _dispatch\n    raise e\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 291, in _dispatch\n    result = getattr(self._webelement, d_call)(*d_args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\appium\\webdriver\\webelement.py\", line 218, in send_keys\n    self._execute(RemoteCommand.SEND_KEYS_TO_ELEMENT, {'text': ''.join(keys), 'value': keys})\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Updating text", "status": "passed", "parameters": [{"name": "elem", "value": "<selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement object at 0x0000024491098D10>"}, {"name": "value", "value": "'1000'"}], "start": 1695030668652, "stop": 1695030669642}, {"name": "Updating text", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error (An unknown server-side error occurred. status='false'. Failed to complete internal method: 'elementSendText args: [NATIVE, xpath=(//*[@resource-id='etTerm' or @id='etTerm'])[1], 0, 5]', details: Failed to send text to 'xpath=(//*[@resource-id='etTerm' or @id='etTerm'])[1]'. ) \n\n", "trace": "  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Final_Proj_Aut_Py\\extensions\\ui_actiuons.py\", line 24, in update_text\n    elem.send_keys(value)\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 232, in send_keys\n    self._dispatch(\"change_value_of\", (self._webelement, self._driver), \"send_keys\", value)\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 294, in _dispatch\n    raise e\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 291, in _dispatch\n    result = getattr(self._webelement, d_call)(*d_args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\appium\\webdriver\\webelement.py\", line 218, in send_keys\n    self._execute(RemoteCommand.SEND_KEYS_TO_ELEMENT, {'text': ''.join(keys), 'value': keys})\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"C:\\Automation\\Hobiz_Automation\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "elem", "value": "<selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement object at 0x0000024491069B10>"}, {"name": "value", "value": "'5'"}], "start": 1695030670338, "stop": 1695030675195}], "parameters": [{"name": "amount", "value": "'1000'"}, {"name": "term", "value": "'5'"}, {"name": "rate", "value": "'2.5'"}, {"name": "save", "value": "True"}], "start": 1695030667746, "stop": 1695030675223}], "attachments": [{"source": "8fa9877b-bfd9-407e-9e37-15ea0729938d-attachment.png", "type": "image/png"}], "start": 1695030667126, "stop": 1695030675224, "uuid": "e2875562-3a83-4c38-8684-8447ebea6296", "historyId": "91ba5437dc241a31496b60115187fa52", "testCaseId": "7e8eca1073d7403bc815e56ae1ddf278", "fullName": "test_cases.test_mobile.TestMobile#test_delete_saved_trans", "labels": [{"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_mobile_driver')"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_mobile"}, {"name": "subSuite", "value": "TestMobile"}, {"name": "host", "value": "BarLaptop"}, {"name": "thread", "value": "15900-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_mobile"}]}